name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Check build (Frontend)
        run: npm run build:frontend
        
      - name: Check build (Backend)
        run: npm run build:backend

  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check commit message format
        run: |
          # Check if commit messages have proper scope tags [FE], [BE], or [QA]
          git log --oneline origin/main..HEAD | while read line; do
            if ! echo "$line" | grep -E '\[(FE|BE|QA)\]'; then
              echo "❌ Commit message missing scope tag: $line"
              echo "Required format: [FE|BE|QA] Description"
              exit 1
            fi
          done
          echo "✅ All commit messages have proper scope tags"
      
      - name: Check for BUGLOG.md updates (if bug fix)
        run: |
          # Check if any commit mentions "fix" or "bug" and BUGLOG.md was updated
          if git log --oneline origin/main..HEAD | grep -iE '(fix|bug)'; then
            if ! git diff --name-only origin/main..HEAD | grep -q "BUGLOG.md"; then
              echo "❌ Bug fix detected but BUGLOG.md was not updated"
              echo "Please update BUGLOG.md with bug details and fix information"
              exit 1
            fi
            echo "✅ BUGLOG.md updated for bug fix"
          else
            echo "✅ No bug fixes detected, BUGLOG.md check skipped"
          fi 